### ISSUE TITLE
Elección del lenguaje de programación

### ISSUE THREAD

**Issue by johnwaves** [migueruiz/Automatricula#10]
¡Hola, @migueruiz! Me han asignado tu repositorio para trabajar en el Objetivo 2. Lo primero que debemos acordar es el lenguaje de programación. ¿Hay alguno en especial que quieras que usemos? Yo había pensado en Go (Golang) por lo que se ha estado comentando en clase. Dime qué te parece o si quieres proponer tú otro cualquierda, me mantengo a la espera 😁

**Comment by migueruiz** [comment]
¡Hola!, disculpa por la tardanza 😔, yo había pensado en typescript, no se si tendrás algún inconveniente en realizarlo con este lenguaje. Saludos!

**Comment by johnwaves** [comment]
> ¡Hola!, disculpa por la tardanza 😔, yo había pensado en typescript, no se si tendrás algún inconveniente en realizarlo con este lenguaje. Saludos!

No te preocupes! De acuerdo, elegimos entonces TypeScript, por mí no hay ningún problema! 🤗
