### ISSUE TITLE
Organización de estructura de datos

### ISSUE THREAD

**Issue by johnwaves** [migueruiz/Automatricula#12]
Hola, @migueruiz 👋. Leyendo las HU y, en concreto [[HU01] Alumno Antonio](#3), he reflexionado sobre qué se debe incluir, por ahora, en el proyecto. Las entidades que he identificado las he organizado como sigue:

## Estudiante
Clase que almacena la información necesaria acerca de cada estudiante: 
- nombre y apellidos
- DNI
- correo
- asignaturas matriculadas

## Asignatura
En esta clase se representan los datos que identifican y caracterizan las asignatuas: 
- código (para identificar a las asignaturas por si hay varias parecidas)
- nombre
- ~horario (se incluye los días que se imparte y la franja horaria para ello)~
- curso (primero, segundo, etc)
- ~grupo (A, B, etc. Esto es para poder asignar cualquier otro grupo en caso de solapamiento y, por tanto, incompatibilidad horaria)~

## Horario
Aquí se asociará a cada estudiante un horario en función de las asignaturas matriculadas. Tendrá un código para identificar el horario para futuras alteraciones, si se estima oportuno.

Dime cómo lo ves, qué cambiarías y/o eliminarías, etc. Espero tu respuesta 😁.

**Comment by migueruiz** [comment]
Hola!, veo de forma correcta la declaraciones, ya que al fin y al cabo son los datos más importantes a tener en cuenta en mi problema. Aunque como te comentare en el #13, no se si faltaría otro más. Muchas gracias por todo 😁.

**Comment by migueruiz** [comment]
Hecho!

**Comment by johnwaves** [comment]
Analizando el problema y lo planteado para empezar con el M0 he determinado lo siguiente: 
- `Estudiante` y `Asignatura` son entidades, teniendo en cuenta los principios del diseño dirigido por dominio (DDD), puesto que resultan ser recursos que pueden cambiar de estado y, tal vez, posteriormente eliminados (un estudiante puede acabar la carrera y dejar de ser estudiante, y una asignatura puede dejar de estar en el plan de estudios).
- `Horario` es un objeto valor, ya que se considera inmutable. Los cambios en el horario generalmente implicarían crear un nuevo horario en lugar de modificar el existente. Por ejemplo, si cambia el horario de una asignatura, no se cambiará el horario en sí, sino que se crearía un nuevo horario para esa asignatura.

Adicionalmente, se ha añadido lo que indico a continuación para poder modelar la estructura que permitirá más adelante ofrecer una mejor solución al problema:
- `Curso`, siendo una entidad al tener identidad propia y duradera en el contexto académico (#16).
- `Grupo`, es un agregado que agrupa entidades (estudiantes), objetos valor (horarios) y entidades relacionadas (asignaturas) en una unidad cohesiva (#17).
