### ISSUE TITLE
Relación estudiantes y asignaturas

### ISSUE THREAD

**Issue by johnwaves** [migueruiz/Automatricula#13]
Hola de nuevo, @migueruiz 👋.

Este issue está relacionado con la [Elección de estructura de datos #12 ](https://github.com/migueruiz/Automatricula/issues/12). Quería preguntarte si las asignaturas para este problema están ya asignadas a un estudiante. Con esto me refiero si el proceso de selección y matriculación de una asignatura viene ya hecho anteriormente y queda fuera del problema a resolver en el proyecto. Si es así, he pensado entonces que sería una buena opción crear una nueva entidad, Matrícula, para gestionar la relación entre estudiantes y asignaturas. Dime cómo lo ves y si habías pensado en otra forma de estructurarlo 😉.

**Comment by migueruiz** [comment]
Hola!, había pensado que quizás el alumno debería tener un atributo que guarde las diferentes asignaturas que tiene, un vector que almacenase los diferentes ID de asignaturas en los que se encuentre, aunque debería ser una estructura que guardase más información, ya que el id de la asignatura te diría por ejemplo "Fundamentos de Redes", pero no te indicaría si es el A, B o cual es. Espero tu respuesta para saber tu opinión 😁.

**Comment by johnwaves** [comment]
> Hola!, había pensado que quizás el alumno debería tener un atributo que guarde las diferentes asignaturas que tiene, un vector que almacenase los diferentes ID de asignaturas en los que se encuentre, aunque debería ser una estructura que guardase más información, ya que el id de la asignatura te diría por ejemplo "Fundamentos de Redes", pero no te indicaría si es el A, B o cual es. Espero tu respuesta para saber tu opinión 😁.

Si lo hacemos así, con los ID de cada asignatura que esté en el array sí que se puede obtener el grupo. Todo es implementar un método que lo busque a partir del ID que le pases como parámetro. Así que se puede hacer sin problema. 

Gracias por tu respuesta, lo modificaré en breve en la estructura y pasaré a escribir el código 🤙🤙

**Comment by migueruiz** [comment]
Perfecto! ✌️

**Comment by johnwaves** [comment]
Por tanto, tanto `Estudiante` como `Asignatura` son entidades siguiendo los principios teóricos del Diseño Dirigido del Dominio (DDD).
