### ISSUE TITLE
¿Qué es un grupo?

### ISSUE THREAD

**Issue by johnwaves** [migueruiz/Automatricula#17]
En HU03 #5 se menciona `grupo` y, aunque el issue esté asignado para el M2, este término resulta relevante para poder proceder con la organización de la estructura base que se debe tratar en el M0. 

Un `grupo` aglutina las asignaturas específicas de un curso. Cada curso puede tener uno o varios grupos. Para cada grupo, una asignatura determinada tiene un horario determinado (día y franja horaria en la que se debe cursar).

**Comment by johnwaves** [comment]
`Grupo`, es un agregado que agrupa entidades (estudiantes), objetos valor (horarios) y entidades relacionadas (asignaturas) en una unidad cohesiva. Esto se añade a la explicación dada en #12 .

**Comment by JJ** [comment]
Los grupos son por asignatura, no por curso. Además, puede haber varios grupos de prácticas por asignatura.
